{{- if .Values.namespace | default dict | dig "create" true }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-ui.labels" . | nindent 4 }}
{{- end }}
